server:
  port: 9002
   
eureka:
  client:
    service-url:
       defaultZone: http://admin:password123@discovery:8761/eureka
       instance:
    prefer-ip-address: false
    
ribbon:
  eureka:
    enabled: true
    
spring:
  datasource:
    url: jdbc:mysql://120.76.210.31:3306/fred_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.jdbc.Driver

    dbcp2:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  application:
    name: fred-user
  

spring.cache:
    #缓存名称
    cache-names: fredCacheName
    #缓存最大数量500条, 缓存失效时间 6个小时
    #guava.spec: maximumSize=500,expireAfterWrite=360m
  # REDIS (RedisProperties)
spring.redis :
    host : 120.76.210.31 # server host
    password : xxxxxx
    port : 6379 # connection port
    pool.max-idle : 8 # pool settings ...
    pool.min-idle : 1
    pool.max-active : 8
    pool.max-wait : -1  # -1 nolimited


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jin.beans

# 解决feign第一次调用超市的错误（断路器超时）
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

# 另外一种方式，关闭断路器超时
# hystrix.command.default.execution.timeout.enabled: false

# 彻底关闭断路器功能 
#feign.hystrix.enable: false
