package com.jin.dao;

import com.jin.beans.SysUser;

public interface SysUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	SysUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysUser record);

}