package com.jin.beans;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_nickname
     *
     * @mbggenerated
     */
    private String user_nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbggenerated
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone_num
     *
     * @mbggenerated
     */
    private String phone_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.rate_level_id
     *
     * @mbggenerated
     */
    private String rate_level_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attractive_value
     *
     * @mbggenerated
     */
    private Integer attractive_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.rose_value
     *
     * @mbggenerated
     */
    private Integer rose_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.image_url
     *
     * @mbggenerated
     */
    private String image_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.money_value
     *
     * @mbggenerated
     */
    private Double money_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_online
     *
     * @mbggenerated
     */
    private Integer is_online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.cur_group_id
     *
     * @mbggenerated
     */
    private String cur_group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param user_name the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_nickname
     *
     * @return the value of sys_user.user_nickname
     *
     * @mbggenerated
     */
    public String getUser_nickname() {
        return user_nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_nickname
     *
     * @param user_nickname the value for sys_user.user_nickname
     *
     * @mbggenerated
     */
    public void setUser_nickname(String user_nickname) {
        this.user_nickname = user_nickname == null ? null : user_nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_id
     *
     * @return the value of sys_user.user_id
     *
     * @mbggenerated
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_id
     *
     * @param user_id the value for sys_user.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone_num
     *
     * @return the value of sys_user.phone_num
     *
     * @mbggenerated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone_num
     *
     * @param phone_num the value for sys_user.phone_num
     *
     * @mbggenerated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.rate_level_id
     *
     * @return the value of sys_user.rate_level_id
     *
     * @mbggenerated
     */
    public String getRate_level_id() {
        return rate_level_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.rate_level_id
     *
     * @param rate_level_id the value for sys_user.rate_level_id
     *
     * @mbggenerated
     */
    public void setRate_level_id(String rate_level_id) {
        this.rate_level_id = rate_level_id == null ? null : rate_level_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.province
     *
     * @return the value of sys_user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.province
     *
     * @param province the value for sys_user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.city
     *
     * @return the value of sys_user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.city
     *
     * @param city the value for sys_user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.country
     *
     * @return the value of sys_user.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.country
     *
     * @param country the value for sys_user.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birthday
     *
     * @return the value of sys_user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birthday
     *
     * @param birthday the value for sys_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sign
     *
     * @return the value of sys_user.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sign
     *
     * @param sign the value for sys_user.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attractive_value
     *
     * @return the value of sys_user.attractive_value
     *
     * @mbggenerated
     */
    public Integer getAttractive_value() {
        return attractive_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attractive_value
     *
     * @param attractive_value the value for sys_user.attractive_value
     *
     * @mbggenerated
     */
    public void setAttractive_value(Integer attractive_value) {
        this.attractive_value = attractive_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.rose_value
     *
     * @return the value of sys_user.rose_value
     *
     * @mbggenerated
     */
    public Integer getRose_value() {
        return rose_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.rose_value
     *
     * @param rose_value the value for sys_user.rose_value
     *
     * @mbggenerated
     */
    public void setRose_value(Integer rose_value) {
        this.rose_value = rose_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.image_url
     *
     * @return the value of sys_user.image_url
     *
     * @mbggenerated
     */
    public String getImage_url() {
        return image_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.image_url
     *
     * @param image_url the value for sys_user.image_url
     *
     * @mbggenerated
     */
    public void setImage_url(String image_url) {
        this.image_url = image_url == null ? null : image_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.money_value
     *
     * @return the value of sys_user.money_value
     *
     * @mbggenerated
     */
    public Double getMoney_value() {
        return money_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.money_value
     *
     * @param money_value the value for sys_user.money_value
     *
     * @mbggenerated
     */
    public void setMoney_value(Double money_value) {
        this.money_value = money_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_online
     *
     * @return the value of sys_user.is_online
     *
     * @mbggenerated
     */
    public Integer getIs_online() {
        return is_online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_online
     *
     * @param is_online the value for sys_user.is_online
     *
     * @mbggenerated
     */
    public void setIs_online(Integer is_online) {
        this.is_online = is_online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.cur_group_id
     *
     * @return the value of sys_user.cur_group_id
     *
     * @mbggenerated
     */
    public String getCur_group_id() {
        return cur_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.cur_group_id
     *
     * @param cur_group_id the value for sys_user.cur_group_id
     *
     * @mbggenerated
     */
    public void setCur_group_id(String cur_group_id) {
        this.cur_group_id = cur_group_id == null ? null : cur_group_id.trim();
    }
}