package com.jin.beans;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_name
     *
     * @mbggenerated
     */
    private String menu_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_path
     *
     * @mbggenerated
     */
    private String menu_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_component
     *
     * @mbggenerated
     */
    private String menu_component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_id
     *
     * @mbggenerated
     */
    private Integer parent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.icon_class
     *
     * @mbggenerated
     */
    private String icon_class;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_hidden
     *
     * @mbggenerated
     */
    private String is_hidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_name
     *
     * @return the value of sys_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenu_name() {
        return menu_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_name
     *
     * @param menu_name the value for sys_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenu_name(String menu_name) {
        this.menu_name = menu_name == null ? null : menu_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_path
     *
     * @return the value of sys_menu.menu_path
     *
     * @mbggenerated
     */
    public String getMenu_path() {
        return menu_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_path
     *
     * @param menu_path the value for sys_menu.menu_path
     *
     * @mbggenerated
     */
    public void setMenu_path(String menu_path) {
        this.menu_path = menu_path == null ? null : menu_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_component
     *
     * @return the value of sys_menu.menu_component
     *
     * @mbggenerated
     */
    public String getMenu_component() {
        return menu_component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_component
     *
     * @param menu_component the value for sys_menu.menu_component
     *
     * @mbggenerated
     */
    public void setMenu_component(String menu_component) {
        this.menu_component = menu_component == null ? null : menu_component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_id
     *
     * @return the value of sys_menu.parent_id
     *
     * @mbggenerated
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_id
     *
     * @param parent_id the value for sys_menu.parent_id
     *
     * @mbggenerated
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.icon_class
     *
     * @return the value of sys_menu.icon_class
     *
     * @mbggenerated
     */
    public String getIcon_class() {
        return icon_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.icon_class
     *
     * @param icon_class the value for sys_menu.icon_class
     *
     * @mbggenerated
     */
    public void setIcon_class(String icon_class) {
        this.icon_class = icon_class == null ? null : icon_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_hidden
     *
     * @return the value of sys_menu.is_hidden
     *
     * @mbggenerated
     */
    public String getIs_hidden() {
        return is_hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_hidden
     *
     * @param is_hidden the value for sys_menu.is_hidden
     *
     * @mbggenerated
     */
    public void setIs_hidden(String is_hidden) {
        this.is_hidden = is_hidden == null ? null : is_hidden.trim();
    }
}